<a href="https://colab.research.google.com/github/sophiannunez18/DSC_110/blob/main/Data_Cleaning_%26_Summarization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# This code was used to import Pandas data into GC, this took the pandas library and shortened the name to pd

import pandas as pd

In [2]:
# This next line of code was used to load files into GC, this link is what we will use to extract information from

df = pd.read_csv ('https://raw.githubusercontent.com/osoliman/DSC110/refs/heads/main/Datasets/nhanes_final.csv')

In [3]:
# The next line of code was used to show the top 5 rows of the data from the link entered above
df.head()

,id,gender,age,race_ethnicity,education,bmi,height_cm,systolic_bp,has_diabetes,hba1c,fasting_glucose
0,130378.0,1.0,43.0,6.0,5.0,27.0,179.5,135.0,2.0,5.6,113.0
1,130379.0,1.0,66.0,3.0,5.0,33.5,174.2,121.0,2.0,5.6,99.0
2,130380.0,2.0,44.0,2.0,3.0,29.7,152.9,111.0,1.0,6.2,156.0
3,130381.0,2.0,5.0,7.0,NaN,23.8,120.1,NaN,2.0,NaN,NaN
4,130382.0,1.0,2.0,3.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN

In [4]:
# The next line of code was used to get the first row from the data

df.head(1)

,id,gender,age,race_ethnicity,education,bmi,height_cm,systolic_bp,has_diabetes,hba1c,fasting_glucose
0,130378.0,1.0,43.0,6.0,5.0,27.0,179.5,135.0,2.0,5.6,113.0

In [5]:
# The next line of code was used to show the last 5 rows of data

df.tail()

,id,gender,age,race_ethnicity,education,bmi,height_cm,systolic_bp,has_diabetes,hba1c,fasting_glucose
11928,142306.0,1.0,9.0,2.0,NaN,15.4,128.0,NaN,2.0,NaN,NaN
11929,142307.0,2.0,49.0,4.0,5.0,NaN,143.8,127.0,1.0,6.2,NaN
11930,142308.0,1.0,50.0,2.0,4.0,26.4,173.3,106.0,2.0,NaN,NaN
11931,142309.0,1.0,40.0,2.0,4.0,25.5,179.1,127.0,2.0,5.2,96.0
11932,142310.0,2.0,80.0,3.0,3.0,27.6,161.7,128.0,2.0,5.3,NaN

In [6]:
# The next line of code was used to show us the size of the table, specifically (num of rows, num of column)

df.shape

(11933, 11)

In [7]:
# The next line of code was used to see the number of rows only

df.shape[0]

11933

In [8]:
# This code was used to print into words how many rows and columns we can see in the data

print(f'this file has {df.shape[0]} row and {df.shape[1]} columns')

this file has 11933 row and 11 columns

Note: The next couple of lines of code will look into Data Cleaning specifically. This is also refered to as Boolean

In [11]:
# If we gave numbers python can tell us if we are true or false

1+1==2

True

In [12]:
# This code is similar to the one above, checking to see if it is true or false

1+1==3

False

In [13]:
# The next line of code is used to obtain an integer of 1

int(True)

1

In [14]:
# The next code is adding on to what we did above, just turns the answer into 1 for true
int(1+1==2)

1

In [15]:
# The next line of code was used to find how many missing values are in the columns

df.isna().sum()

id                    0
gender                0
age                   0
race_ethnicity        0
education          4139
bmi                3462
height_cm          3434
systolic_bp        4416
has_diabetes        193
hba1c              5218
fasting_glucose    8261
dtype: int64

In [16]:
# The next code is an addition of the one above but instead finding the percentage of values that are missing in each column

df.isna().mean() * 100

id                  0.000000
gender              0.000000
age                 0.000000
race_ethnicity      0.000000
education          34.685326
bmi                29.011984
height_cm          28.777340
systolic_bp        37.006620
has_diabetes        1.617364
hba1c              43.727478
fasting_glucose    69.228191
dtype: float64

In [20]:
# The next line of code was used to drop rows where specficially diabetes has missing data

df_clean = df.dropna(subset=['has_diabetes']).copy()

# The next line of code was used to check how many of these rows you no longer have in your data

print(f"Started with {len(df)} rows")
print(f"Now have {len(df_clean)} rows")

Started with 11933 rows
Now have 11740 rows

In [22]:
# The next line of code was used to fill any systolic BP using mean

mean_bp = df_clean['systolic_bp'].mean()
df_clean['systolic_bp'] = df_clean['systolic_bp'].fillna(mean_bp)

In [24]:
# The next line of code was used to make sure the code from above worked

df_clean['systolic_bp'].isna().sum()

np.int64(0)

Note: The next lines of code will deal with transforming variables within our data

In [26]:
# This next line of code will be used to creat BMI categories

df['bmi_category'] = pd.cut(df['bmi'],
                            bins=[0, 18.5, 25, 30, 100],
                            labels=['Underweight', 'Normal', 'Overweight', 'Obese'])

In [27]:
# The next line of code was use to check our work from above

df['bmi_category'].value_counts()

bmi_category
Obese          2666
Normal         2400
Overweight     2189
Underweight    1216
Name: count, dtype: int64

In [53]:
# The next line of code was used to show all the values that appear in the education column

df['education'].unique()

array([ 5.,  3., nan,  2.,  4.,  1.,  9.])

In [68]:
# The next line of code was used to create a map dictionary, this is adjusted based on what is shown in your data dictionary depending on dataset

education_map = {
    1.0: 'less than 9th grade',
    2.0: '9-11th grade',
    3.0: 'High school grad',
    4.0: 'Some college or AA degree',
    5.0: 'College graduate',
    9.0: 'Do not know'
}

# The next line of code was used to apply the mapping we did above

df['education_label'] = df['education'].map(education_map)

In [69]:
# This next line of code was used to make sure our work from above worked properly

df['education_label'].value_counts()

education_label
College graduate             2625
Some college or AA degree    2370
High school grad             1749
9-11th grade                  666
less than 9th grade           373
Do not know                    11
Name: count, dtype: int64

Note: The next lines of code are related to data summarization

In [57]:
# The next line of code was used to calculate mean

df['systolic_bp'].mean()

# The next line of case was used to calculate standard deviation

df['systolic_bp'].mean()

# The next line of code was use to obtain both mean and standard deviation
df['systolic_bp'].describe()

count    7517.000000
mean      119.288546
std        18.561052
min        61.000000
25%       106.000000
50%       117.000000
75%       130.000000
max       232.000000
Name: systolic_bp, dtype: float64

In [58]:
# The next line of code was used to get the median

df['age'].median()

37.0

In [59]:
# The next line of code was used to find the IQR for only the 25th and 75th percentiles

df['age'].quantile([0.25, 0.75])

0.25    13.0
0.75    62.0
Name: age, dtype: float64

In [60]:
# The next line of code was used to obtain IQR at all percentiles and both mean + SD

df['age'].describe()

count    1.193300e+04
mean     3.831786e+01
std      2.560199e+01
min      5.397605e-79
25%      1.300000e+01
50%      3.700000e+01
75%      6.200000e+01
max      8.000000e+01
Name: age, dtype: float64

In [61]:
# The next line of code was used to obtain the mode of the data

df['age'].mode()

0    80.0
Name: age, dtype: float64

Note: The next lines of code refer to categorical and one variables

In [70]:
# The next line of code was used to show counts within our data

df['education_label'].value_counts()

education_label
College graduate             2625
Some college or AA degree    2370
High school grad             1749
9-11th grade                  666
less than 9th grade           373
Do not know                    11
Name: count, dtype: int64

In [71]:
# The next line of code is adding to the count we did above with percentages

df['education_label'].value_counts(normalize=True)

education_label
College graduate             0.336798
Some college or AA degree    0.304080
High school grad             0.224403
9-11th grade                 0.085450
less than 9th grade          0.047857
Do not know                  0.001411
Name: proportion, dtype: float64

Note: The next lines of data will look into categorical and two variables

In [72]:
# The next line of code was used to create a cross-tab of our dataset

pd.crosstab(df['has_diabetes'], df['bmi_category'])

bmi_category  Underweight  Normal  Overweight  Obese
has_diabetes
1.0                     4     109         233    504
2.0                  1211    2251        1886   2042
3.0                     0      39          70    120
9.0                     1       1           0      0

In [73]:
# The next line of code is adding from our cross tab above with percentages

pd.crosstab(df['has_diabetes'], df['bmi_category'], normalize='index') * 100

bmi_category  Underweight     Normal  Overweight      Obese
has_diabetes
1.0              0.470588  12.823529   27.411765  59.294118
2.0             16.387009  30.460081   25.520974  27.631935
3.0              0.000000  17.030568   30.567686  52.401747
9.0             50.000000  50.000000    0.000000   0.000000

Note: The next line of code will look at a mix of variables

In [75]:
# The next line of code will be used to group by having diabetes and bmi

df.groupby('has_diabetes') ['bmi'].mean()

has_diabetes
1.0    32.981412
2.0    26.439797
3.0    32.068559
9.0    19.250000
Name: bmi, dtype: float64